### ISSUE TITLE
Usage of bools for sets

### ISSUE THREAD

**Issue by mmacheerpuppy** [logic-building/functional-go#132]
Hi all.

I noticed you are using bools for your sets. Generally when creating sets in Golang, as far as I am familiar, it is more efficient to declare types of `map[stirng]struct{}` to shave off the bytes used to implement Bool. I really have enjoyed some of the approaches used in this library and it helped me make some progress in creating map reduce semantics for my own types.

**Comment by mmacheerpuppy** [comment]
See https://github.com/golang-collections/collections/blob/master/set/set.go for some considerable idioms

**Comment by logic-building** [comment]
thank you for your comment. I will update the logic in future release.
